logging:
  severity: "warn"
  colorize: true
  filter:
    - password
    - confirm_password

database_url: "mysql://root@localhost:3306/test_settings_test"
host: 0.0.0.0
name: test_settings
port: 3000
port_reuse: true
process_count: 1
redis_url: "redis://localhost:6379"
secret_key_base: ox7cTo_408i4WZkKZ_5OZZtB5plqJYhD4rxrz2hriA4

# ssl_key_file:
# ssl_cert_file:

session:
  key: "amber.session"
  store: "signed_cookie"
  expires: 0

secrets:
  description: "Store your test secrets credentials and settings here."

